@startuml

title Hashtags Graph

card "Plant2ML" as Plant2ML #salmon
card "PlantUML\n~#diagrams" as PlantUML
card "ML\n~#machinelearning" as ML
card "~#llm" as LLM
card "~#ai" as AI
card "CLIPS\n~#expertsystems" as ES
card "~#generativeai" as GenerativeAI
card Applications
card "~#timeseries" as Timeseries
card "~#nlp" as nlp
card "~#finance" as Finance
card "~#designpatterns" as DesignPatterns
card "Autonomic Computing\n~#autonomic" as Autonomic
card DOM

PlantUML -> Plant2ML
ML --> Plant2ML
ML --> LLM
AI --> ML
AI --> ES
ML --> GenerativeAI
GenerativeAI --> Plant2ML
Applications -> Timeseries
Timeseries --> Finance
Applications --> nlp
Plant2ML --> Applications
Plant2ML <- DesignPatterns
LLM --> Plant2ML
ES --> Plant2ML
Autonomic --> Plant2ML
Plant2ML <-- DOM
Applications --> Finance
nlp -> Finance

@enduml